spring:
  cache:
    caffeine:
      spec: maximumSize=100,expireAfterWrite=10s

  sql:
    init:
      mode: always

  datasource:
    url: jdbc:mysql://localhost:3306/nbcam
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

jwt:
  secret: "bXktc3VwZXItc2VjcmV0LWtleS1mb3Itand0LTIwMjY="
  expiration: 3600000

