'use client'

import { useEffect, useState } from 'react'
import { ArrowLeft, CheckCircle2, CreditCard, IceCreamBowl, Loader2 } from 'lucide-react'
import { useRouter, useSearchParams } from 'next/navigation'

const API_BASE_URL = 'http://localhost:8080'
const money = (n: number) => `${new Intl.NumberFormat('ko-KR').format(n)}원`
type Order = { orderId?: number; orderNumber?: string; totalAmount: number; paymentId?: number }
export default function PaymentPage() {
  const router = useRouter(); const params = useSearchParams(); const orderId = params.get('orderId') || ''
  const [order, setOrder] = useState<Order | null>(null); const [state, setState] = useState<'ready' | 'loading' | 'success'>('ready'); const [error, setError] = useState('')
  useEffect(() => { if (!orderId) { setError('주문 정보가 없습니다.'); return }; fetch(`${API_BASE_URL}/api/orders/${orderId}`, { headers: { Authorization: `Bearer ${localStorage.getItem('accessToken') || ''}` } }).then(async (response) => { if (!response.ok) throw new Error(`주문 정보를 불러오지 못했습니다. (${response.status})`); const result = await response.json(); setOrder(result.data ?? result) }).catch((requestError) => { console.error('[v0] 결제 주문 조회 실패:', requestError); setError(requestError instanceof Error ? requestError.message : '주문 정보를 불러오지 못했습니다.') }) }, [orderId])
  const confirm = async () => { if (!order) return; setState('loading'); setError(''); const response = await fetch(`${API_BASE_URL}/api/payments/confirm`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('accessToken') || ''}` }, body: JSON.stringify({ orderId: order.orderId ?? Number(orderId), result: 'SUCCESS', amount: order.totalAmount }) }); const data = await response.json(); if (!response.ok) { setError(response.status === 409 ? '이미 승인된 결제입니다.' : data.message || '결제에 실패했습니다.'); setState('ready'); return } setState('success') }
  return <main className="min-h-screen bg-[#f5f7fa] text-[#0a1f3d]"><header className="border-b border-[#dce5ef] bg-white px-6 py-5"><div className="mx-auto flex max-w-3xl items-center justify-between"><button onClick={() => router.push('/')} className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-[#1265d8] text-white"><IceCreamBowl /></span><b>Two게더</b></button><button onClick={() => router.push('/orders')} className="text-sm font-bold text-[#52657c]">주문 내역</button></div></header><section className="mx-auto max-w-xl px-6 py-14">{state === 'success' ? <div className="rounded-3xl border border-[#d8e1ec] bg-white p-10 text-center shadow-sm"><CheckCircle2 className="mx-auto size-16 text-[#159c98]" /><p className="mt-6 text-xs font-bold tracking-[.22em] text-[#159c98]">PAYMENT COMPLETE</p><h1 className="mt-3 text-3xl font-bold">결제가 완료되었습니다</h1><p className="mt-3 text-sm text-[#64748b]">주문번호 {order?.orderNumber || '확인 중'}</p><button onClick={() => router.push(`/orders/${orderId}`)} className="mt-8 w-full rounded-2xl bg-gradient-to-r from-[#0a1f3d] to-[#1265d8] px-6 py-4 font-bold text-white">주문 상세 보기</button></div> : <><button onClick={() => router.back()} className="flex items-center gap-2 text-sm font-bold text-[#52657c]"><ArrowLeft /> 돌아가기</button><div className="mt-8 rounded-3xl border border-[#d8e1ec] bg-white p-8 shadow-sm"><p className="text-xs font-bold tracking-[.22em] text-[#159c98]">PAYMENT</p><h1 className="mt-3 text-3xl font-bold">결제하기</h1><div className="mt-8 flex items-center justify-between border-b border-[#e6edf5] pb-6"><div><p className="font-bold">{order?.orderNumber || '주문번호 확인 중'}</p><p className="mt-1 text-sm text-[#64748b]">주문번호 ID: {orderId}</p></div><strong className="text-2xl">{money(order?.totalAmount ?? 0)}</strong></div><div className="mt-6 flex items-center gap-3 rounded-2xl bg-[#f5f7fa] p-4"><CreditCard className="text-[#1265d8]" /><span className="text-sm font-semibold">모의 결제 · 카드 결제</span></div>{error && <p role="alert" className="mt-5 rounded-xl bg-[#fff1f0] px-4 py-3 text-sm font-semibold text-[#c0392b]">{error}</p>}<button disabled={state === 'loading'} onClick={confirm} disabled={!order || state === 'loading'} className="mt-8 flex w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-[#0a1f3d] to-[#1265d8] px-6 py-4 font-bold text-white disabled:opacity-60">{state === 'loading' && <Loader2 className="animate-spin" />}결제하기</button></div></>}</section></main>
}
